* ツールの設定

** Emacs

#+begin_src emacs-lisp
(emacs-version)
#+end_src

#+RESULTS:
: GNU Emacs 31.0.50 (build 1, aarch64-apple-darwin23.6.0, NS appkit-2487.70 Version 14.6.1 (Build 23G93))
:  of 2024-08-09

see https://github.com/ataka/emacs-d.git

** Eza

Better =ls=

#+begin_src
  brew install eza
#+end_src

** fzf

=zoxide= との連携で力を発揮する Fazzy Finder

#+begin_src
  brew install fzf
#+end_src

** Git

- =.gitconfig=

** GNU Screen

- =.screenrc=

** oh my posh

*** oh my posh のインストール

#+begin_src
  brew install jandedobbeleer/oh-my-posh/oh-my-posh
#+end_src

** WezTerm

*** WezTerm のインストール

#+begin_src
  brew install --cask wezterm
#+end_src

*** WezTerm の使い方

- =Cmd + T= タブを新しく作る
- =Cmd + W= タブを閉じる

** zoxide

Better =cd=

#+begin_src
  brew install zoxide
#+end_src

** zsh

- =.zshrc=
- =.zprofile=

*** zsh (homebrew 版)

#+begin_src
  brew install zsh
#+end_src

**** zsh (homebrew 版) の設定

=/etc/shells= に次の行を追加します。

#+begin_src
  /opt/homebrew/bin/zsh
#+end_src

その後、ログイン・シェルの変更を実施します。

#+begin_src
  chsh -s /opt/homebrew/bin/zsh
#+end_src

* プログラミング言語の設定

** Mermaid

*** mmdc

Mermaid のソースコードから画像等を作成するコマンドラインツール。

**** mmdc のインストール

#+begin_src 
npm install -g @mermaid-js/mermaid-cli
#+end_src

**** Rakefile のサンプル

次の Rakefile を用意しておくと、ビルドが楽になります。

#+begin_src ruby
  PLANTUML = "/opt/homebrew/bin/plantuml"

  task :default => :uml

  desc "UML 図を更新する"
  task :uml => %w[
    foo.png
  ]

  rule '.png' => '.mmdc' do |t|
    sh "mmdc -i #{t.source} -o #{t.name}"
  end
#+end_src

** PlantUML

*** plantuml

PlantUML のソースコードから画像等を作成するコマンドラインツール。

**** plantuml のインストール

#+begin_src 
brew install plantuml
#+end_src

**** Rakefile のサンプル

次の Rakefile を用意しておくと、ビルドが楽になります。

#+begin_src ruby
  PLANTUML = "/opt/homebrew/bin/plantuml"

  task :default => :uml

  desc "UML 図を更新する"
  task :uml => %w[
    foo.png
  ]

  rule '.png' => '.plantuml' do |t|
    sh "#{PLANTUML} #{t.source}"
  end
#+end_src

* フォントの設定

** UDEV Gothic

- https://github.com/yuru7/udev-gothic

BIZ UDGothic と JetBrains Mono を組み合わせたフォント。

JetBrains Mono は Ligature に対応しています。

Nerd Fonts に対応した =UDEVGothic_NF_v2.0.0.zip= をダウンロードしています。

** Victor Mono

- https://rubjo.github.io/victor-mono/

Ligature に対応した英文フォント。
